### ISSUE TITLE
Testing rx.placemark

### ISSUE THREAD

**Issue by deceroainfinito** [RxSwiftCommunity/RxCoreLocation#15]
I have this GeolocationService:

```
import CoreLocation

import RxSwift
import RxCoreLocation

class GeolocationService: NSObject {

  var locationManager: CLLocationManager!

  var currentPlacemark: CLPlacemark?
  var currentLocation: CLLocation? {
    return currentPlacemark?.location
  }

  var disposeBag = DisposeBag()

  convenience init(withLocationManager loc: CLLocationManager) {
    self.init()
    locationManager = loc
    locationManager.desiredAccuracy = kCLLocationAccuracyNearestTenMeters
    locationManager.requestWhenInUseAuthorization()
    locationManager.startUpdatingLocation()

    locationManager.rx.placemark.subscribe(onNext: { [unowned self] placemark in
      self.currentPlacemark = placemark
    }).disposed(by: disposeBag)
  }

  deinit {
    locationManager.stopUpdatingLocation()
  }

  func getCurrentLocation() -> (latitude: Double, longitude: Double)? {
    guard let lat = currentLocation?.coordinate.latitude,
      let lon = currentLocation?.coordinate.longitude else { return nil }
    return (latitude: lat, longitude: lon)
  }

  func getCurrentAddress() -> Address? {
    guard let cPlacemark = currentPlacemark else { return nil}

    let address = Address(street: cPlacemark.name, zipCode: cPlacemark.postalCode, city: cPlacemark.locality, country: cPlacemark.country)

    return address
  }
}
```

Despite any design flaw it's working properly. 
My question is, how can I unit test the placemark subscription?
Due to this dependency any other method's test would be trivial if I could just be able to test the subscription.

Looking forward for any thoughts, thanks in advance!

**Comment by bobgodwinx** [comment]
@deceroainfinito Thanks for you question. Actually this is not the `placemark` problem. It's more related to the `location` property, the `placemark` is computed here from this [private function](https://github.com/RxSwiftCommunity/RxCoreLocation/blob/master/Sources/CLLocationManagerEvents%2BRx.swift#L62) and I wanted it to always return a `non-optional` value. However everything depends on the `location` . The `CLLocationManager` returns an `Optional(nil)` first and later an `Optional(CLLocation)`.  The only hint I have to unit testing this is to subclass the `CLLocationManager` but I don't think really it's the best idea. but you can use it to return a location and then the `placemark`.

**Comment by deceroainfinito** [comment]
Thanks @bobgodwinx !!

I'm mocking the CLLocationManager with

```
class MockLocationManager: CLLocationManager {

  var mockLocation: CLLocation?
  override var location: CLLocation? {
    return mockLocation
  }
}
```

Within the unit testing `setUp` function I'm doing this

```
aPlacemark = MKPlacemark(coordinate: coords, addressDictionary: address)

mockLS = MockLocationManager()
mockLS.mockLocation = aPlacemark.location

geoService = GeolocationService(withLocationManager: mockLS)
```

and, so far, I just did get to trigger the 'rx.location' subscription!

Somehow I can't get the rx.placemark subscription to work so I'm just refactoring my Geoservice class to work with locations instead of placemarks. Quite simple to refractor in fact.

Botom line: I'm doing something wrong  with the placemark's subscriptions, I don't know what, but since I put location's subscription to work, I'm good with that.
