### ISSUE TITLE
Add support to RxSwift 4.4.0

### ISSUE THREAD

**Issue by xPryds** [RxSwiftCommunity/RxCoreLocation#18]

**Comment by bobgodwinx** [comment]
@xPryds this is working with `RxSwift 4.4.0` there is no update needed. There is no breaking API changes in `RxSwift 4.4.0`

**Comment by alexvndre** [comment]
I think @xPryds is talking about dependencies like with Cocoapods:
```
$ pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "RxSwift":
  In snapshot (Podfile.lock):
    RxSwift (= 4.4.0, ~> 4.0, ~> 4.3)

  In Podfile:
    RxCocoa (~> 4.0) was resolved to 4.4.0, which depends on
      RxSwift (~> 4.0)

    RxCoreLocation (~> 1.3.1) was resolved to 1.3.1, which depends on
      RxCoreLocation/Core (= 1.3.1) was resolved to 1.3.1, which depends on
        RxSwift (~> 4.3.1)

    RxMKMapView (~> 4.0) was resolved to 4.3.0, which depends on
      RxSwift (~> 4.3)
```
With these dependencies:
```
  pod 'RxSwift',	'~> 4.0'
  pod 'RxCocoa',    	'~> 4.0'
  pod 'RxMKMapView',	'~> 4.0'
  pod 'RxCoreLocation', '~> 1.3.1'
```

**Comment by bobgodwinx** [comment]
Ok I get what he means now. Thanks very @alexvbush, Anyone interested in sending me a PR? My hands are quite tied.

**Comment by DarkDirectX** [comment]
> Ok I get what he means now. Thanks very @alexvbush, Anyone interested in sending me a PR? My hands are quite tied.

Created PR.

**Comment by sarangborude** [comment]
Hi guys, is this resolved?
I see the tests on CI seems to fail on the PR. 
When will this be done?
Your help is greatly appreciated

**Comment by bobgodwinx** [comment]
This is fixed in the last release
