### ISSUE TITLE
Unable to resolve dependency 

### ISSUE THREAD

**Issue by learnwithgabbar** [RxSwiftCommunity/RxCoreLocation#29]
The package dependency graph can not be resolved; unable find any available tag for the following requirements:

https://github.com/RxSwiftCommunity/RxCoreLocation.git — 1.4.0..<2.0.0

**Comment by bobgodwinx** [comment]
if you are using swift package manager just set it to `1.4.0` it should work because the tag is there.

**Comment by grangej** [comment]
@bobgodwinx you need to release a new version, the 1.4.0 is actually missing the changes for the Package.swift:

https://github.com/RxSwiftCommunity/RxCoreLocation/compare/1.4.0...master

**Comment by bobgodwinx** [comment]
Fix. you can now use version `1.4.1` and  it has all changes from master
