### ISSUE TITLE
didReceiveRegion available for iOS 9.3 in RxCoreLocation 1.3.2

### ISSUE THREAD

**Issue by PabloDomine** [RxSwiftCommunity/RxCoreLocation#31]
Hi, 
I was working with a native CoreLocation implementation for a geofencing feature and now I'm moving everything to RxSwift.
It was working just fine before, my project's deployment target is iOS 9.0, but I don't understand why the API below is marked for iOS 9.3 or above if the three CoreLocation methods that is using are available from iOS 4.0/5.0.

```
    @available(iOS 9.3, OSX 10.11, *)
    public var didReceiveRegion: RxCocoa.ControlEvent<CLRegionEvent> { get }
```

Could this be an issue? 
Thank you!

**Comment by bobgodwinx** [comment]
There is a lot of instabilities related to version `iOS 9.0` and as rule I just decided to cut it to `iOS 9.3`. But you can always fork the project and downgrade to `iOS 9.0` if that will do for you and then later come back when your project is updated.

**Comment by PabloDomine** [comment]
Hope not to find tons of instabilities! Thank you for your help and quick response!
