### ISSUE TITLE
Failure converting from Optional(<...>) to CLLocationManagerDelegate

### ISSUE THREAD

**Issue by Pattio** [RxSwiftCommunity/RxCoreLocation#42]
Hi,

first of all thank you for maintaining this library 🙏

We have been using RxCoreLocation for some time now and every then and now we see this crash:

`Fatal error: Failure converting from Optional(<GjlTsjYFHdNgFERt: 0x282062300>) to CLLocationManagerDelegate: file RxCocoa/RxCocoa.swift, line 153`

At first we saw that users that crashed had jailbroken devices so immediate though was that they are just messing with location manger. However, more recently we received few crashes that happened on devices that were not jailbroken i.e.:

`Fatal error: Failure converting from Optional(<GjlTsjYFHdNgFERt: 0x280045400>) to CLLocationManagerDelegate: file RxCocoa/RxCocoa.swift, line 153`.

We are not doing anything magical apart from subscribing to `didChangeAuthorization`, `didUpdateLocations`.

This is affecting only super small fraction of our users, but nevertheless it is interesting why this could happen. Perhaps you have any insights?

**Comment by bobgodwinx** [comment]
Hi @Pattio 

Thanks for reporting. 

The line of code indicated is actually in the main library `RxCoca` which indicates a fatal error. 

From what I see it looks like error is coming from `didChangeAuthorization ` in iOS14 correct? 
Let me know of the device affected is iOS14 then this means we need to make a patch because the delegate method was deprecated by Apple and we're trying to access it still and hence we crash.

**Comment by Pattio** [comment]
From crashlog it seems that crash happens on `didUpdateLocations`:

`Reactive<A>.didUpdateLocations.getter + 20`.

90% of crashes happen on iOS 13 and 10% on iOS 14. 

Here is our binding code if that's of any help:

```swift
private func initializeBindings() {
    locationManager.rx.didChangeAuthorization
        .map { $0.status }
        .bind(to: authorizationStatus)
        .disposed(by: disposeBag)
    
    authorizationStatus
        .map { status in status == .authorizedWhenInUse || status == .authorizedAlways }
        .bind(to: isAuthorized)
        .disposed(by: disposeBag)
    
    locationManager.rx
        .didUpdateLocations
        .compactMap { $0.locations.last }
        .do(
            onNext: { [weak self] location in
                if let locationRequest = self?.locationRequest {
                    locationRequest(location)
                    self?.locationRequest = nil
                    self?.stopUpdating()
                }
            }
        )
        .bind(to: lastLocation)
        .disposed(by: disposeBag)
    
    if #available(iOS 14.0, *) {
        locationManager.rx.didChangeAuthorization
            .map { $0.manager.accuracyAuthorization == .fullAccuracy }
            .bind(to: fullAccuracy)
            .disposed(by: disposeBag)
    }
}
```

**Comment by bobgodwinx** [comment]
```swift
    if #available(iOS 14.0, *) {
        locationManager.rx.didChangeAuthorization
            .map { $0.manager.accuracyAuthorization == .fullAccuracy }
            .bind(to: fullAccuracy)
            .disposed(by: disposeBag)
    }
```

The above API has been deprecated for iOS 14 and we did mark it as deprecated we need to make that fix

**Comment by bobgodwinx** [comment]
We need to provide another API where you can get the `accuracyAuthorization`

**Comment by Pattio** [comment]
Yes it has been deprecated, but it is still available in iOS 14.0 so for time being we just used it as it is. However, that still wouldn't explain crashes on iOS 13, yes?

**Comment by bobgodwinx** [comment]
There a fix on the `develop` branch can you try it and give me feedbacks on it ? 

```
pod 'RxCoreLocation', :git => 'https://github.com/RxSwiftCommunity/RxCoreLocation.git', :branch => 'develop'
```

Tested it on iOS 13 and iOS 14 works pretty well.

**Comment by Pattio** [comment]
Hey, sure, will point to this branch and see if there are still crashes, however, since this is super rare crash it might take a while. I'll re-open this issue if crash re-appears. Thanks and have a nice day/night

**Comment by cythb** [comment]
Hi @Pattio 
I encountered the same problem as you. This crash seems caused by a failure to convert the delegate object type. It doesn't seem to fix anything with this modified code.
Also, I found that the devices with the problem are jailbroken. Can you see if the crashed device is jailbroken?

**Comment by cythb** [comment]
Here is my crash snapshot.
![image](https://user-images.githubusercontent.com/1787428/110755641-22702180-8284-11eb-8f1d-0d82179dbea4.png)

**Comment by Pattio** [comment]
Hi @cythb, in our case it's not only jailbroken devices, to be precise only 52% are jailbroken devices which are probably crashing as they are messing with location services, not sure with the reason regarding those other 48%, but with next release we will try to switch to updated branch and see if it helps

**Comment by bobgodwinx** [comment]
Just keep me posted from the branch so I can help if needed cheers mate.
