### ISSUE TITLE
How to use with RxSwift 3.6.1?

### ISSUE THREAD

**Issue by RafaelPlantard** [RxSwiftCommunity/RxCoreLocation#7]
Is it possible to use with RxSwift 3?

**Comment by bobgodwinx** [comment]
@RafaelPlantard The project started already with the `RxSwift 4.0` release and I wonder if it makes sense to release an older version. I might be wrong, but if there are more people with `RxSwift 3.0` then we might do a special backward compatibility. But at the moment it requires `RxSwift 4.0`

**Comment by RafaelPlantard** [comment]
I'm working in a fork using RxSwift 3.6.1, can you see [it](https://github.com/Swift-Yah/RxCoreLocation/tree/rxswift-3.0)?

**Comment by bobgodwinx** [comment]
@RafaelPlantard ok :) you win We're going to make a build + a release for old version but it will not be on cocoapods. But just like you did in your `fork` we will do and used a backward tag it. Can create a PR from the fork?

**Comment by RafaelPlantard** [comment]
Sure ;)

**Comment by RafaelPlantard** [comment]
I made a PR to `master`, because I didn't know for which branch/tag to point.

**Comment by bobgodwinx** [comment]
@RafaelPlantard I have created a branch called `rxswift-3x` you can point the PR to that branch and we can merge and tag it from there.

**Comment by RafaelPlantard** [comment]
@bobgodwinx Done!

**Comment by bobgodwinx** [comment]
@RafaelPlantard  so you can find the [Legacy Support here](https://github.com/RxSwiftCommunity/RxCoreLocation/releases/tag/0.9.0)
